import * as React from 'react'
import type { Metadata } from 'next'
import { cn } from '@/helpers/lib/utils'
import NavList from '@/components/ui/nav-list'

export const metadata: Metadata = {
  title: 'Create Next App',

  description: 'Generated by create next app',
}

export default function ChatLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <section className={cn('min-h-screen w-full flex bg-white text-black')}>
      {' '}
      {/* Side Bar */}
      <NavList />
      {/* Home Page */}
      <div className="w-full">{children}</div>
    </section>
  )
}
