import * as React from 'react'
import type { Metadata } from 'next'
import './globals.css'
import { ReactQueryProvider } from '@/helpers/providers/ReactQueryProvider'
import { WebSocketContextProvider } from '@/helpers/providers/WebSocketProvider'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: 'Create Next App',

  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <WebSocketContextProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
          <Toaster richColors />
        </WebSocketContextProvider>
      </body>
    </html>
  )
}
