import * as React from 'react'
import type { Metadata } from 'next'
import './globals.css'
import { ReactQueryProvider } from '@/helpers/providers/ReactQueryProvider'
import NavList from '@/components/NavBar/NavList'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Create Next App',

  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen w-full flex bg-white text-black')}>
        {/* Side Bar */}
        <NavList />
        {/* Home Page */}
        <div className="w-full">
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </div>
      </body>
    </html>
  )
}
