import * as React from 'react'
import type { Metadata } from 'next'
import './globals.css'
import { ReactQueryProvider } from '@/helpers/providers/ReactQueryProvider'

export const metadata: Metadata = {
  title: 'Create Next App',

  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  )
}
